#!/bin/sh

set -o pipefail -o errexit -o nounset

cd "$(dirname "$0")/.."

compiler='/proj/isaac/tools/sjasmplus/build/sjasmplus'


sjasmplus \
  --syntax=ab \
  --sym=build/loader.sym \
  --lst=build/loader.lst \
  src/loader.asm
