#!/bin/sh

set -o pipefail -o errexit -o nounset

cd "$(dirname "$0")/.."

./bzpack/bzpack pristine/loading.scr build/loading.pck -ue2 -o -e -r
./bzpack/bzpack pristine/moonrn.bin build/code.pck -ue2 -o -e -r
