#!/bin/sh

set -o errexit -o nounset -o pipefail
cd "$(dirname "$0")/.."

breakpoint_addr () {
  grep breakpoint ./build/loader.sym | awk '{ print $3 }'
}

breakpoint=$(breakpoint_addr || true)
if [ "$breakpoint" == "" ]; then
  echo "No breakpoints found"
else
  echo "Breakpoint $breakpoint"
  fuse ./moo.tap --debugger-command="break $(breakpoint_addr)"
fi
